In [48]:
import pandas as pd 
import numpy as np
import tensorflow as ts
import seaborn as sns

In [35]:
data = pd.read_csv("/Users/joulesss/Documents/DOCTORADO/Materias/AnaliticaComputacional/Proyecto2_Final/data_encoded.csv")

data.head(5)

,periodo,cole_area_ubicacion,cole_bilingue,cole_caracter,cole_cod_mcpio_ubicacion,cole_jornada,cole_mcpio_ubicacion,cole_naturaleza,cole_nombre_establecimiento,estu_genero,...,fami_personashogar,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global
0,20162,1,0,2,15238,1,DUITAMA,1,COLEGIO GUILLERMO LEON VALENCIA,1.0,...,NaN,NaN,NaN,NaN,61.0,59.0,63.0,57.0,56.0,295.0
1,20142,0,0,2,15759,1,SOGAMOSO,1,INSTITUCION EDUCATIVA LA INDEPENDENCIA,0.0,...,6.0,1.0,0.0,0.0,52.0,55.0,54.0,60.0,54.0,277.0
2,20152,1,0,1,15835,6,TURMEQUE,1,I.E. TECNICA INDUSTRIAL,0.0,...,3.0,0.0,0.0,1.0,55.0,52.0,50.0,53.0,47.0,254.0
3,20172,1,0,2,15176,1,CHIQUINQUIRA,1,I.E. TECNICA PIO ALBERTO FERRO PEÑA,0.0,...,5.5,0.0,0.0,1.0,59.0,58.0,46.0,51.0,45.0,253.0
4,20172,1,0,2,15759,1,SOGAMOSO,0,COLEGIO COOPERATIVO REYES PATRIA,1.0,...,3.5,1.0,1.0,1.0,75.0,66.0,70.0,65.0,64.0,335.0

## Trtamiento de variables

In [45]:

data['nivel_educacion_padres'] = round((data['fami_educacionmadre']+data['fami_educacionpadre'])/2,0)# tomar el máximo nivel entre ambos padres

data['hacinamiento'] = data['fami_personashogar'] / (data['fami_cuartoshogar'] + 1)

In [ ]:

def clasificar_ingles(x):
    if 0 <= x <= 36:
        return 0   # Pre A1
    elif 37 <= x <= 57:
        return 1   # A1
    elif 58 <= x <= 70:
        return 2   # A2
    elif 71 <= x <= 100:
        return 3   # B1
    else:
        return None
 
data["nivel_ingles"] = data["punt_ingles"].apply(clasificar_ingles)

In [ ]:
var = ["cole_bilingue", "cole_jornada","cole_area_ubicacion","cole_naturaleza", "cole_caracter","cole_area_ubicacion", "cole_mcpio_ubicacion",
       "fami_tienecomputador","fami_tieneinternet","fami_estratovivienda", "nivel_educacion_padres","hacinamiento","nivel_ingles"]


data_p1 = data[var].copy()


y = data_p1["nivel_ingles"] #var interes 

# Municipality kept only for analysis/plots
municipio = data_p1["cole_mcpio_ubicacion"]

# Features for model: exclude target and municipality
X = data_p1.drop(columns=["nivel_ingles", "cole_mcpio_ubicacion"])

,cole_bilingue,cole_jornada,cole_area_ubicacion,cole_naturaleza,cole_caracter,cole_area_ubicacion,cole_mcpio_ubicacion,fami_tienecomputador,fami_tieneinternet,fami_estratovivienda,nivel_educacion_padres,hacinamiento,nivel_ingles
1,0,1,0,1,2,0,SOGAMOSO,1.0,0.0,1.0,2.0,2.000000,1.0
2,0,6,1,1,1,1,TURMEQUE,0.0,0.0,1.0,2.0,1.000000,1.0
3,0,1,1,1,2,1,CHIQUINQUIRA,0.0,0.0,2.0,4.0,1.375000,2.0
4,0,1,1,0,2,1,SOGAMOSO,1.0,1.0,3.0,8.0,1.166667,3.0
5,0,6,1,0,3,1,SOGAMOSO,1.0,0.0,2.0,4.0,1.750000,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
100044,0,6,1,1,1,1,GUACAMAYAS,0.0,0.0,1.0,2.0,1.250000,1.0
100045,-1,1,0,1,3,0,MUZO,0.0,0.0,1.0,1.0,1.500000,1.0
100046,0,1,1,1,2,1,CHIQUINQUIRA,0.0,0.0,1.0,2.0,0.750000,2.0
100047,-1,2,0,1,3,0,DUITAMA,0.0,0.0,2.0,3.0,1.000000,1.0
100048,0,6,1,0,3,1,TUNJA,1.0,1.0,3.0,6.0,1.250000,3.0